config/routes.rb
Rails.application.routes.draw do
  resources :entities
  root 'entities#index'
  devise_for :users

  post '/ajax_show_password' => 'entities#show_password', :as => "show_password"

end

app/models/entity.rb
class Entity
  include Mongoid::Document
  include Mongoid::Attributes::Dynamic
  field :name, type: String
  field :username, type: String
  field :description, type: String
  field :url, type: String
  field :password, type: String
  belongs_to :user

  attr_accessor :master_password

  #Callback
  before_save :crypt_password
  #Scope
  scope :all_by_user, -> (user_id) { where(:user_id => user_id).order(name: :asc) }
  scope :find_by_and_user, -> (user_id) { where(:user_id => user_id) }

  #Crypt Password with Master password
  def crypt_password 
    if !master_password
      raise "Master Password not valid"
    end
    puts "Crypting user password with master password ..."
    self.password = AESCrypt.encrypt(password, master_password)
  end

  #Delete removed custom attributes
  def check_changed_attributes(keys)
    (self.attributes.keys - keys - ["_id", "user_id"]).each do |key|
      delete_custom_attributes(key.to_s.to_sym)
    end
  end

  #Retunr custom attributes keys
  def custom_attributes
    (self.attributes.keys-self.attribute_names).map { |x| x.to_sym }
  end

  #Delete custom attributes
  def delete_custom_attributes(key)
    self.unset(key.to_s.to_sym)
  end

  #Decrypt and show password
  def self.show_password(master_password,entity_id,current_user)
  	entity = Entity.find(:id=> entity_id,:user_id=>current_user.id)
  	if !entity
  		raise "Entity not found"
  	end
  	AESCrypt.decrypt(entity.password, master_password)
  end

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :trackable, :validatable

  ## Database authenticatable
  field :email,              type: String, default: ""
  field :encrypted_password, type: String, default: ""

  ## Recoverable
  field :name,              type: String
  field :surname,           type: String  
  field :master_password,   type: String

  ## Recoverable
  field :reset_password_token,   type: String
  field :reset_password_sent_at, type: Time

  ## Rememberable
  field :remember_created_at, type: Time

  ## Trackable
  field :sign_in_count,      type: Integer, default: 0
  field :current_sign_in_at, type: Time
  field :last_sign_in_at,    type: Time
  field :current_sign_in_ip, type: String
  field :last_sign_in_ip,    type: String

  ## Confirmable
  # field :confirmation_token,   type: String
  # field :confirmed_at,         type: Time
  # field :confirmation_sent_at, type: Time
  # field :unconfirmed_email,    type: String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, type: Integer, default: 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    type: String # Only if unlock strategy is :email or :both
  # field :locked_at,       type: Time

  # Return Surname and Name
  def fullname
    surname.to_s.capitalize+" "+name.to_s.capitalize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  #Only authenticated user
	before_filter :authenticate_user!
end

app/controllers/entities_controller.rb
class EntitiesController < ApplicationController
  before_action :set_entity, only: [:show, :edit, :update, :destroy]
  before_action :check_changed_attributes, only: [ :update ]

  respond_to :html

  def index
    @entities = Entity.all_by_user(current_user.id)
    respond_with(@entities)
  end

  def show
    respond_with(@entity)
  end

  def new
    @entity = Entity.new
    respond_with(@entity)
  end

  def edit
  end

  def create
    @entity = Entity.new(entity_params)
    @entity.user=current_user
    @entity.save
    respond_with(@entity)
  end

  def update
    @entity.user=current_user
    @entity.update(entity_params)
    respond_with(@entity)
  end

  def destroy
    @entity.destroy
    respond_with(@entity)
  end

  def show_password
    render :json => Entity.show_password(params[:master_password],params[:entity_id],current_user).to_json
  end

  private

    def set_entity
      @entity = Entity.find(params[:id])
    end

    def entity_params
      params.require(:entity).permit!
    end

    def check_changed_attributes
      @entity.check_changed_attributes(entity_params.keys)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/entities_helper.rb
module EntitiesHelper
end

app/views/entities/_form.html.haml
= form_for @entity, :html => {:class => "form-horizontal"} do |f|
  - if @entity.errors.any?
    #error_explanation
      %h2= "#{pluralize(@entity.errors.count, "error")} prohibited this entity from being saved:"
      %ul
        - @entity.errors.full_messages.each do |msg|
          %li= msg

  .form-group
    = f.label :name, 'Name*', :class=>"col-md-2 control-label"
    .col-md-8
      = f.text_field :name, :class=>"form-control", :required=>true
  .form-group
    = f.label :description, 'Description', :class=>"col-md-2 control-label"
    .col-md-8
      = f.text_area :description, :class=>"form-control"
  .form-group
    = f.label :username, 'Username*', :class=>"col-md-2 control-label"
    .col-md-8
      = f.text_field :username, :class=>"form-control", :required=>true  
  .form-group
    = f.label :url, 'URL', :class=>"col-md-2 control-label"
    .col-md-8
      = f.text_field :url, :class=>"form-control"
  .form-group
    = f.label :password, 'Password*', :class=>"col-md-2 control-label"
    .col-md-8
      = f.password_field :password, :class=>"form-control", :required=>true
  .form-group
    = f.label :master_password, 'Master Password*', :class=>"col-md-2 control-label"
    .col-md-8
      = f.password_field :master_password, :class=>"form-control", :required=>true

  .form-group
    .col-md-8.col-md-offset-2
      %table#table_attribute.table.table-condensed.table-hover      
        %thead
          %tr
            %th Key
            %th Value
            %th
        %tbody
          - @entity.custom_attributes.each do |key|
            %tr
              %td
                %strong=key
              %td
                =@entity[key]
                =hidden_field_tag "entity[#{key}]", @entity[key]
              %td
                .pull-right
                  = button_tag :onclick=>"$(this).closest('tr').remove()", :class=>"btn btn-raised btn-xs btn-danger" do
                    %i.mi.md-18.bottom delete
  .form-group
    .col-md-offset-2
      =link_to "#", :class=>"btn btn-info btn-xs add_attribute_modal" do
        %i.mi.md-18.bottom add_circle_outline
        Add Attribute

  .form-group
    .col-md-offset-2
      = f.submit 'Save', :class=>"btn btn-raised btn-primary"
      = link_to 'Back', entities_path, :class=>"btn btn-raised btn-default"

app/views/entities/_modal_add_attribute.html.haml
#modal_add_attribute.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{:type => "button", "data-dismiss" => "modal"} ×
        %h2 Add Attribute
      .modal-body
        %br
        .form-horizontal

          .form-group
            = label_tag :key_attribute, 'Key', :class=>"col-md-3 control-label"
            .col-md-8
              = text_field_tag :key_attribute, nil, :class=>"form-control", :required=>true

          .form-group
            = label_tag :value_attribute, 'Value', :class=>"col-md-3 control-label"
            .col-md-8
              = text_field_tag :value_attribute, nil, :class=>"form-control", :required=>true


      .modal-footer
        =link_to 'Add', '#', :'data-dismiss'=>"modal", :class=>"btn btn-raised btn-primary add_attribute"
          

app/views/entities/edit.html.haml
.page-header
  %h1 Editing entity

.well
  = render 'form'
  = render 'modal_add_attribute'

app/views/entities/index.html.haml
.page-header
  .pull-right
    =link_to new_entity_path, :class=>"btn btn-primary" do
      %i.mi.md-18.bottom add_circle_outline
      New Password
  %h1 Password Manager

.list-group
  - @entities.each do |entity|
    .list-group-item
      %a.entry-master-password{:href=>"#", :'data-object-id'=>entity.id}
        .row-action-primary        
          %i.material-icons{:id=>"icon_#{entity.id}"} lock
      .row-content
        = link_to entity_path(entity) do
          .action-secondary
            %i.material-icons info
        %h4.list-group-item-heading
          -if entity.url
            = link_to entity.name, entity.url, :target=>"_blank", :class=>"master-link"
          -else
            = entity.name
        .row
          .col-md-6
            %dl.dl-horizontal.dl-horizontal-left
              %dt Username
              %dd=entity.username
            %dl.dl-horizontal.dl-horizontal-left
              %dt Password
              %dd 
                %span.label.label-default{:id=>"hidden_passsword_#{entity.id.to_s}"}
                  HIDDEN
                %span.label.label-primary{:id=>"show_passsword_#{entity.id.to_s}", :style=>"display: none;"}
          .col-md-6
            -if entity.description
              %dl
                %dt Description
                %dd=entity.description
            -entity.custom_attributes.each do |key|
              %dl.dl-horizontal.dl-horizontal-left
                %dt=key
                %dd= entity[key]
      .list-group-separator
  

app/views/entities/new.html.haml
.page-header
  %h1 New entity

.well
  = render 'form'
  = render 'modal_add_attribute'

app/views/entities/show.html.haml
.page-header
  .pull-right
    .btn-toolbar
      =link_to root_path, :class=>"btn btn-raised btn-default" do
        %i.mi.md-18.bottom chevron_left
        Back
      =link_to edit_entity_path(@entity), :class=>"btn btn-raised btn-warning" do
        %i.mi.md-18.bottom edit
        Edit
      =link_to @entity, :method => :delete, :data => { confirm: 'Are you sure?' }, :class=>"btn btn-raised btn-danger" do
        %i.mi.md-18.bottom delete
        Delete

  %h1
    %small Site
    = @entity.name

.well
  %dl.dl-horizontal
    %dt Name
    %dd= @entity.name  
  %dl.dl-horizontal
    %dt Description
    %dd= @entity.description
  %dl.dl-horizontal
    %dt Username
    %dd= @entity.username
  %dl.dl-horizontal
    %dt URL
    %dd= link_to @entity.url, @entity.url, :target=>"_blank", :class=>"master-link" 
  - @entity.custom_attributes.each do |key|
    %dl.dl-horizontal
      %dt=key
      %dd= @entity[key]
  %dl.dl-horizontal
    %dt Password
    %dd
      .row        
        .col-md-3
          %span.label.label-default{:id=>"hidden_passsword_#{@entity.id.to_s}"}
            HIDDEN      
          %span.label.label-primary{:id=>"show_passsword_#{@entity.id.to_s}", :style=>"display: none;"}
        .col-md-1{:style=>"margin-top: -15px;"}
          =button_tag :class=> "btn btn-primary btn-xs btn-fab entry-master-password", :'data-object-id'=>@entity.id do
            %i.material-icons{:id=>"icon_#{@entity.id}"} lock

app/views/layouts/_flash_messages.html.haml
-if notice
	%span.notice-snackbar{:msg=>notice}
-if alert
	.row
		.col-md-8.col-md-offset-2
			%p.alert.alert-danger=alert

app/views/layouts/_header.html.haml
.navbar.navbar-inverse
  .container-fluid
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-inverse-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => root_path } 
        %i.mi.md-36{:style=>"margin-top: -3px"} security
    - if user_signed_in?
      .navbar-collapse.collapse.navbar-inverse-collapse
        .middle-navbar-form
          %form.navbar-form.navbar-left
            .form-group.is-empty
              %input#nav-search.form-control{:placeholder => "Search", :type => "text", :style=>"width: 300px;"} 
        %ul.nav.navbar-nav.navbar-right          
          %li.dropdown
            %a.dropdown-toggle{:href=>"#", :'data-target'=>"#", :'data-toggle'=>"dropdown"}
              =current_user.email
              %b.caret
            %ul.dropdown-menu
              //%li=link_to('Edit', edit_user_path(current_user), :method => :delete)
              //%li.divider
              %li=link_to('Logout', destroy_user_session_path, :method => :delete)

app/views/layouts/_modal_master_password.html.haml
#modal_master_password.modal.fade
  .modal-dialog
    .modal-content
      .modal-header
        %button.close{:type => "button", "data-dismiss" => "modal"} ×
        %h2 Master Password
      .modal-body
        %br
        .alert.alert-danger{:id=>"error_decrypt_div", :style=>"display: none;"}
          %strong Errror decrypting password!
          Please check master password. 

        =form_tag "#", :'data-ref-action'=>show_password_path, :class=>"form-horizontal", :id=>"check-master-password-form"
        .form-group
          = label_tag :master_password, 'Insert Master Password', :class=>"col-md-4 control-label"
          .col-md-8
            = password_field_tag :master_password, nil, :class=>"form-control", :required=>true
            = hidden_field_tag :entity_id, nil
      .modal-footer
        =link_to 'Show Password', "#", :class=>"btn btn-raised btn-primary check-master-password-btn"
          

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Password Manager
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = csrf_meta_tags

    // Use Google Font: Roboto
    = google_webfonts_init({google: ['Roboto Slab', 'Roboto'] })
  %body
    = render 'layouts/header'
    = render 'layouts/flash_messages'
    .container
      = yield
      
    = render 'layouts/modal_master_password'



    = javascript_include_tag 'application', 'data-turbolinks-track' => true